/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LayoutFooter: typeof import('./src/components/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./src/components/LayoutHeader.vue')['default']
    LayoutNav: typeof import('./src/components/LayoutNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
